import { ArticleStatus, PrismaClient } from '@prisma/client';

type ArticleCategory = 'GUIDES' | 'INSPIRATION' | 'CULTURE' | 'GASTRONOMY';

type ArticleSeed = {
  category: ArticleCategory;
  title: string;
  excerpt: string;
  imageUrl: string;
  author: string;
  readTime: number;
  isFeatured?: boolean;
  publishedAt: Date;
  focus: string;
  destination: string;
  practicalTip: string;
};

const AUTHORS = [
  'Azure Horizon Editorial',
  'Minh Anh Travel Desk',
  'Linh Tran',
  'Hoang Nam',
  'Thu Ha',
];

function slugify(title: string): string {
  return title
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

function imageUrl(id: string): string {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=80`;
}

function buildContent(article: ArticleSeed): string {
  return [
    `<p>${article.excerpt}</p>`,
    `<h2>Vì sao chủ đề này đáng quan tâm?</h2>`,
    `<p>${article.focus} không chỉ là một gợi ý du lịch đơn lẻ, mà còn là cách để du khách hiểu rõ hơn về nhịp sống, khí hậu, văn hóa địa phương và khả năng di chuyển thực tế tại ${article.destination}. Một hành trình được chuẩn bị tốt sẽ giúp giảm rủi ro phát sinh, tránh lãng phí thời gian và giữ được tinh thần thoải mái trong suốt chuyến đi.</p>`,
    `<p>Với khách lần đầu trải nghiệm, sai lầm thường nằm ở việc xếp lịch quá dày, đánh giá thấp thời gian di chuyển hoặc chọn điểm đến chỉ vì hình ảnh đẹp. Cách tiếp cận đúng là bắt đầu từ mục tiêu chuyến đi: nghỉ dưỡng, khám phá văn hóa, chụp ảnh, ẩm thực hay kết hợp nhiều nhu cầu trong một lịch trình cân bằng.</p>`,
    `<h2>Thời điểm và nhịp lịch trình</h2>`,
    `<p>Thời điểm lý tưởng nên được chọn dựa trên thời tiết, lượng khách và tính chất hoạt động. Nếu hành trình có nhiều hoạt động ngoài trời, hãy ưu tiên khung giờ sáng sớm hoặc cuối chiều. Nếu chuyến đi thiên về nghỉ dưỡng, cần dành đủ khoảng trống giữa các hoạt động để khách không có cảm giác bị chạy theo lịch.</p>`,
    `<p>Một lịch trình tốt thường có một điểm nhấn chính mỗi ngày, thêm một đến hai hoạt động phụ và luôn có khoảng nghỉ. Với nhóm gia đình hoặc nhóm có người lớn tuổi, lịch trình càng cần rõ ràng về thời gian di chuyển, điểm đón trả, bữa ăn và mức độ vận động.</p>`,
    `<h2>Kinh nghiệm thực tế khi chuẩn bị</h2>`,
    `<p>${article.practicalTip}</p>`,
    `<p>Du khách nên kiểm tra lại giấy tờ cá nhân, điều kiện vé, chính sách hủy đổi và thông tin liên hệ hỗ trợ trước ngày khởi hành. Với các tour có lịch khởi hành cố định, việc xác nhận lại giờ tập trung và số điện thoại điều phối là bước nhỏ nhưng rất quan trọng.</p>`,
    `<h2>Chi phí, kỳ vọng và trải nghiệm</h2>`,
    `<p>Chi phí hợp lý không nhất thiết là chi phí thấp nhất. Một tour đáng chọn là tour có mô tả minh bạch, dịch vụ đúng nhu cầu, lịch trình không quá tải và đội ngũ hỗ trợ phản hồi rõ ràng. Khi so sánh các lựa chọn, hãy nhìn vào tổng giá trị thay vì chỉ so giá vé ban đầu.</p>`,
    `<p>Điểm khác biệt lớn nhất của một chuyến đi tốt nằm ở cảm giác sau khi trở về: khách nhớ được những khoảnh khắc cụ thể, hiểu hơn về nơi mình đã đến và không bị mệt mỏi vì những phát sinh đáng lẽ có thể chuẩn bị trước.</p>`,
    `<h2>Gợi ý từ Azure Horizon</h2>`,
    `<p>Azure Horizon khuyến nghị du khách lưu lại thông tin đặt chỗ, theo dõi email xác nhận và liên hệ đội ngũ hỗ trợ nếu có thay đổi về số khách, lịch trình hoặc nhu cầu đặc biệt. Càng trao đổi sớm, khả năng xử lý càng chủ động và trải nghiệm tổng thể càng ổn định.</p>`,
  ].join('\n');
}

const articles: ArticleSeed[] = [
  {
    category: 'GUIDES',
    title: 'Lịch trình 3 ngày khám phá Hà Nội cho người lần đầu ghé thăm',
    excerpt: 'Gợi ý cách sắp xếp ba ngày ở Hà Nội với nhịp đi vừa phải, đủ phố cổ, di sản, ẩm thực và khoảng nghỉ để chuyến đi không bị quá tải.',
    imageUrl: imageUrl('photo-1500530855697-b586d89ba3ee'),
    author: AUTHORS[0],
    readTime: 8,
    isFeatured: true,
    publishedAt: new Date('2026-05-01T08:00:00.000Z'),
    focus: 'Lịch trình Hà Nội ba ngày',
    destination: 'Hà Nội',
    practicalTip: 'Ngày đầu nên dành cho phố cổ, hồ Hoàn Kiếm và ẩm thực đường phố; ngày thứ hai phù hợp với Văn Miếu, Hoàng thành Thăng Long và các bảo tàng; ngày cuối nên nhẹ hơn với cà phê, mua quà và chuẩn bị ra sân bay.',
  },
  {
    category: 'GUIDES',
    title: 'Cách chọn tour biển miền Trung theo mùa gió và ngân sách',
    excerpt: 'Biển miền Trung đẹp quanh năm nhưng mỗi mùa có điều kiện thời tiết khác nhau. Bài viết giúp bạn chọn điểm đến, thời gian và gói dịch vụ phù hợp.',
    imageUrl: imageUrl('photo-1507525428034-b723cf961d3e'),
    author: AUTHORS[1],
    readTime: 7,
    publishedAt: new Date('2026-04-29T08:00:00.000Z'),
    focus: 'Chọn tour biển theo mùa',
    destination: 'Đà Nẵng, Nha Trang và Quy Nhơn',
    practicalTip: 'Nếu ưu tiên tắm biển, hãy kiểm tra dự báo gió và sóng trước khi đặt. Nếu đi cùng trẻ nhỏ, nên chọn resort gần trung tâm, ít phải di chuyển và có phương án hoạt động trong nhà khi thời tiết xấu.',
  },
  {
    category: 'GUIDES',
    title: 'Checklist trước ngày khởi hành để tránh quên giấy tờ và vật dụng quan trọng',
    excerpt: 'Một danh sách kiểm tra thực tế giúp du khách chuẩn bị giấy tờ, hành lý, thanh toán và thông tin liên hệ trước khi lên đường.',
    imageUrl: imageUrl('photo-1488646953014-85cb44e25828'),
    author: AUTHORS[2],
    readTime: 6,
    publishedAt: new Date('2026-04-27T08:00:00.000Z'),
    focus: 'Checklist khởi hành',
    destination: 'mọi hành trình nội địa và quốc tế',
    practicalTip: 'Hãy chụp lại căn cước, hộ chiếu, voucher khách sạn, vé điện tử và lưu offline trên điện thoại. Với nhóm đông người, nên chỉ định một người giữ danh sách số điện thoại khẩn cấp và mã đặt chỗ.',
  },
  {
    category: 'GUIDES',
    title: 'Đi tour cùng gia đình có trẻ nhỏ: cách chọn lịch trình ít mệt',
    excerpt: 'Kinh nghiệm chọn tour, giờ bay, khách sạn, bữa ăn và hoạt động phù hợp khi đi cùng trẻ nhỏ hoặc người lớn tuổi.',
    imageUrl: imageUrl('photo-1500534314209-a25ddb2bd429'),
    author: AUTHORS[3],
    readTime: 8,
    publishedAt: new Date('2026-04-25T08:00:00.000Z'),
    focus: 'Du lịch gia đình',
    destination: 'các điểm nghỉ dưỡng Việt Nam',
    practicalTip: 'Không nên chọn lịch trình đổi khách sạn liên tục. Mỗi ngày chỉ nên có một hoạt động chính, ưu tiên điểm tham quan có nhà vệ sinh sạch, chỗ nghỉ chân và thời gian di chuyển dưới một giờ.',
  },
  {
    category: 'GUIDES',
    title: 'Kinh nghiệm đọc mô tả tour để không hiểu nhầm dịch vụ bao gồm',
    excerpt: 'Hướng dẫn đọc kỹ phần bao gồm, không bao gồm, phụ thu, chính sách trẻ em và điều kiện hủy đổi trước khi thanh toán tour.',
    imageUrl: imageUrl('photo-1450101499163-c8848c66ca85'),
    author: AUTHORS[4],
    readTime: 7,
    publishedAt: new Date('2026-04-23T08:00:00.000Z'),
    focus: 'Đọc điều kiện tour',
    destination: 'mọi điểm đến',
    practicalTip: 'Hãy chú ý các dòng nhỏ như phụ thu phòng đơn, vé tham quan tự túc, bữa ăn không bao gồm và điều kiện hoàn tiền. Nếu có điểm chưa rõ, nên hỏi nhân viên trước khi đặt thay vì xử lý sau khi phát sinh.',
  },
  {
    category: 'GUIDES',
    title: 'Lần đầu đi tour nước ngoài cần chuẩn bị gì?',
    excerpt: 'Từ hộ chiếu, visa, bảo hiểm, tiền tệ đến cách giữ liên lạc, đây là những điều cần biết trước chuyến đi nước ngoài đầu tiên.',
    imageUrl: imageUrl('photo-1488085061387-422e29b40080'),
    author: AUTHORS[0],
    readTime: 9,
    publishedAt: new Date('2026-04-21T08:00:00.000Z'),
    focus: 'Chuẩn bị tour nước ngoài',
    destination: 'các hành trình quốc tế',
    practicalTip: 'Hộ chiếu nên còn hạn ít nhất sáu tháng. Ngoài tiền mặt, hãy chuẩn bị thẻ thanh toán quốc tế, eSIM hoặc roaming và lưu địa chỉ khách sạn bằng ngôn ngữ địa phương.',
  },
  {
    category: 'GUIDES',
    title: 'Cách chọn khách sạn trong tour: vị trí quan trọng hơn số sao?',
    excerpt: 'Số sao khách sạn không phải yếu tố duy nhất. Vị trí, giờ nhận phòng, bữa sáng và khả năng di chuyển mới là những điểm cần cân nhắc kỹ.',
    imageUrl: imageUrl('photo-1566073771259-6a8506099945'),
    author: AUTHORS[1],
    readTime: 6,
    publishedAt: new Date('2026-04-19T08:00:00.000Z'),
    focus: 'Chọn khách sạn trong tour',
    destination: 'các thành phố du lịch',
    practicalTip: 'Nếu lịch trình có nhiều thời gian tự do, khách sạn gần trung tâm sẽ tiết kiệm chi phí taxi và giúp buổi tối linh hoạt hơn. Nếu đi nghỉ dưỡng, hãy ưu tiên không gian, tiện ích và bãi biển riêng.',
  },
  {
    category: 'GUIDES',
    title: 'Nên đặt tour sớm bao lâu để có giá tốt và lịch đẹp?',
    excerpt: 'Đặt sớm giúp có thêm lựa chọn về ngày khởi hành, hạng phòng và ưu đãi, nhưng cần hiểu rõ điều kiện hủy đổi để tránh rủi ro.',
    imageUrl: imageUrl('photo-1506784983877-45594efa4cbe'),
    author: AUTHORS[2],
    readTime: 6,
    publishedAt: new Date('2026-04-17T08:00:00.000Z'),
    focus: 'Thời điểm đặt tour',
    destination: 'tour nội địa và quốc tế',
    practicalTip: 'Với mùa cao điểm, nên đặt trước bốn đến tám tuần. Với lễ Tết hoặc tour quốc tế cần visa, thời gian chuẩn bị nên dài hơn để tránh tăng giá vé máy bay và hết phòng đẹp.',
  },
  {
    category: 'GUIDES',
    title: 'Hướng dẫn xử lý khi cần đổi lịch hoặc hủy tour',
    excerpt: 'Các bước cần làm khi kế hoạch thay đổi: kiểm tra điều kiện hủy, chuẩn bị mã đặt chỗ, liên hệ hỗ trợ và theo dõi trạng thái xử lý.',
    imageUrl: imageUrl('photo-1497366754035-f200968a6e72'),
    author: AUTHORS[3],
    readTime: 7,
    publishedAt: new Date('2026-04-15T08:00:00.000Z'),
    focus: 'Đổi lịch và hủy tour',
    destination: 'mọi booking có lịch khởi hành',
    practicalTip: 'Khi gửi yêu cầu hỗ trợ, hãy cung cấp mã đặt chỗ, ngày khởi hành, số khách và lý do thay đổi. Thông tin càng đầy đủ, nhân viên càng tra cứu nhanh và phản hồi chính xác hơn.',
  },
  {
    category: 'GUIDES',
    title: 'Cách giữ sức khỏe trong chuyến đi nhiều điểm tham quan',
    excerpt: 'Một chuyến đi dày hoạt động cần chuẩn bị thể lực, nước uống, giấc ngủ và cách ăn uống hợp lý để không hụt năng lượng giữa hành trình.',
    imageUrl: imageUrl('photo-1500534314209-a25ddb2bd429'),
    author: AUTHORS[4],
    readTime: 6,
    publishedAt: new Date('2026-04-13T08:00:00.000Z'),
    focus: 'Sức khỏe khi du lịch',
    destination: 'các tour khám phá nhiều ngày',
    practicalTip: 'Đừng bỏ bữa sáng, luôn mang nước, thuốc cá nhân và một đôi giày đã quen chân. Nếu có bệnh nền, nên báo trước với đơn vị tổ chức để được tư vấn lịch trình phù hợp.',
  },

  {
    category: 'INSPIRATION',
    title: 'Những khoảnh khắc khiến một chuyến đi trở nên đáng nhớ',
    excerpt: 'Du lịch không chỉ là đến nhiều nơi, mà là những thời điểm nhỏ khiến bạn thấy mình thực sự hiện diện trong hành trình.',
    imageUrl: imageUrl('photo-1500534314209-a25ddb2bd429'),
    author: AUTHORS[0],
    readTime: 7,
    publishedAt: new Date('2026-04-11T08:00:00.000Z'),
    focus: 'Cảm hứng du lịch chậm',
    destination: 'những hành trình cá nhân',
    practicalTip: 'Hãy để lịch trình có khoảng trống cho những điều bất ngờ: một quán cà phê nhỏ, cuộc trò chuyện với người địa phương hoặc một buổi chiều chỉ ngồi nhìn thành phố chuyển màu.',
  },
  {
    category: 'INSPIRATION',
    title: 'Vì sao bình minh luôn là phần thưởng đẹp nhất của người đi xa',
    excerpt: 'Dậy sớm trong chuyến đi không chỉ để chụp ảnh, mà để nhìn thấy nhịp sống địa phương bắt đầu theo cách rất riêng.',
    imageUrl: imageUrl('photo-1500530855697-b586d89ba3ee'),
    author: AUTHORS[1],
    readTime: 6,
    publishedAt: new Date('2026-04-09T08:00:00.000Z'),
    focus: 'Trải nghiệm bình minh',
    destination: 'biển, núi và đô thị cổ',
    practicalTip: 'Hãy chuẩn bị áo khoác nhẹ, kiểm tra hướng mặt trời và đến điểm ngắm trước ít nhất hai mươi phút. Những phút chờ đợi thường là phần đáng nhớ nhất.',
  },
  {
    category: 'INSPIRATION',
    title: 'Du lịch một mình: tự do, tỉnh táo và trưởng thành hơn',
    excerpt: 'Đi một mình không cô đơn nếu bạn chuẩn bị tốt, biết giới hạn an toàn và chọn trải nghiệm phù hợp với tính cách.',
    imageUrl: imageUrl('photo-1500534314209-a25ddb2bd429'),
    author: AUTHORS[2],
    readTime: 8,
    publishedAt: new Date('2026-04-07T08:00:00.000Z'),
    focus: 'Du lịch một mình',
    destination: 'các thành phố an toàn và dễ di chuyển',
    practicalTip: 'Nên chọn nơi lưu trú trung tâm, báo lịch trình cho người thân và luôn có phương án di chuyển về khách sạn trước khi trời quá muộn.',
  },
  {
    category: 'INSPIRATION',
    title: 'Một chuyến đi có thể thay đổi cách ta nhìn về công việc',
    excerpt: 'Rời khỏi nhịp sống quen thuộc giúp nhiều người nhìn lại ưu tiên, năng lượng và cách cân bằng giữa làm việc và nghỉ ngơi.',
    imageUrl: imageUrl('photo-1497215728101-856f4ea42174'),
    author: AUTHORS[3],
    readTime: 7,
    publishedAt: new Date('2026-04-05T08:00:00.000Z'),
    focus: 'Du lịch và cân bằng',
    destination: 'những điểm nghỉ dưỡng yên tĩnh',
    practicalTip: 'Nếu mục tiêu là nạp lại năng lượng, đừng chọn lịch trình quá nhiều điểm check-in. Hãy ưu tiên giấc ngủ, thiên nhiên và thời gian không bị thông báo công việc chen vào.',
  },
  {
    category: 'INSPIRATION',
    title: 'Đi để hiểu rằng mỗi thành phố đều có một nhịp thở riêng',
    excerpt: 'Từ tiếng rao buổi sáng đến ánh đèn buổi tối, mỗi thành phố kể câu chuyện của mình bằng những chi tiết rất nhỏ.',
    imageUrl: imageUrl('photo-1494526585095-c41746248156'),
    author: AUTHORS[4],
    readTime: 6,
    publishedAt: new Date('2026-04-03T08:00:00.000Z'),
    focus: 'Cảm nhận thành phố',
    destination: 'Hà Nội, Huế, Hội An và Sài Gòn',
    practicalTip: 'Hãy thử đi bộ một đoạn ngắn không theo bản đồ, nhưng vẫn giữ an toàn. Đôi khi những con hẻm, tiệm sách và hàng ăn nhỏ mới là nơi giữ linh hồn thành phố.',
  },
  {
    category: 'INSPIRATION',
    title: 'Nghỉ dưỡng đúng nghĩa là học cách không vội',
    excerpt: 'Một kỳ nghỉ tốt không cần lịch dày đặc. Đôi khi giá trị lớn nhất là một buổi sáng không có cuộc hẹn nào.',
    imageUrl: imageUrl('photo-1507525428034-b723cf961d3e'),
    author: AUTHORS[0],
    readTime: 6,
    publishedAt: new Date('2026-04-01T08:00:00.000Z'),
    focus: 'Nghỉ dưỡng chậm',
    destination: 'các khu nghỉ ven biển',
    practicalTip: 'Hãy chọn resort hoặc khách sạn có không gian đủ tốt để bạn không phải di chuyển liên tục. Một kỳ nghỉ dưỡng thành công là khi chính nơi lưu trú cũng trở thành một phần trải nghiệm.',
  },
  {
    category: 'INSPIRATION',
    title: 'Những cung đường khiến người ta muốn quay lại',
    excerpt: 'Có những con đường không nổi tiếng nhất, nhưng lại để lại cảm giác tự do và rộng mở lâu hơn cả điểm đến cuối cùng.',
    imageUrl: imageUrl('photo-1469854523086-cc02fe5d8800'),
    author: AUTHORS[1],
    readTime: 7,
    publishedAt: new Date('2026-03-30T08:00:00.000Z'),
    focus: 'Cảm hứng road trip',
    destination: 'đường ven biển và cao nguyên',
    practicalTip: 'Nếu đi cung đường dài, hãy chia chặng hợp lý, kiểm tra thời tiết và không cố chạy xe vào lúc mệt. Cảnh đẹp chỉ đáng giá khi hành trình vẫn an toàn.',
  },
  {
    category: 'INSPIRATION',
    title: 'Du lịch cùng người thân: giá trị nằm ở thời gian bên nhau',
    excerpt: 'Một chuyến đi gia đình có thể không hoàn hảo tuyệt đối, nhưng lại là cơ hội hiếm để mọi người thật sự ở cạnh nhau.',
    imageUrl: imageUrl('photo-1500534314209-a25ddb2bd429'),
    author: AUTHORS[2],
    readTime: 7,
    publishedAt: new Date('2026-03-28T08:00:00.000Z'),
    focus: 'Du lịch gia đình cảm xúc',
    destination: 'những điểm đến phù hợp nhiều thế hệ',
    practicalTip: 'Hãy để mỗi thành viên được chọn ít nhất một hoạt động mình thích. Sự tham gia đó giúp chuyến đi trở thành trải nghiệm chung thay vì lịch trình do một người quyết định.',
  },
  {
    category: 'INSPIRATION',
    title: 'Khi thiên nhiên giúp ta lắng lại',
    excerpt: 'Núi, rừng, biển và sông luôn có cách nhắc con người chậm lại, thở sâu hơn và nhìn rõ điều mình cần.',
    imageUrl: imageUrl('photo-1441974231531-c6227db76b6e'),
    author: AUTHORS[3],
    readTime: 6,
    publishedAt: new Date('2026-03-26T08:00:00.000Z'),
    focus: 'Chữa lành bằng thiên nhiên',
    destination: 'núi rừng và vùng biển yên tĩnh',
    practicalTip: 'Hãy chọn hoạt động vừa sức như đi bộ nhẹ, ngắm hoàng hôn hoặc chèo thuyền chậm. Không cần biến một chuyến nghỉ thành thử thách thể lực.',
  },
  {
    category: 'INSPIRATION',
    title: 'Lưu giữ chuyến đi bằng câu chuyện thay vì chỉ bằng ảnh',
    excerpt: 'Ảnh đẹp rất quan trọng, nhưng những ghi chú ngắn về cảm xúc, âm thanh và con người gặp trên đường mới khiến ký ức sống lâu hơn.',
    imageUrl: imageUrl('photo-1455390582262-044cdead277a'),
    author: AUTHORS[4],
    readTime: 5,
    publishedAt: new Date('2026-03-24T08:00:00.000Z'),
    focus: 'Ký ức du lịch',
    destination: 'mọi hành trình',
    practicalTip: 'Mỗi tối, hãy ghi lại ba điều đáng nhớ nhất trong ngày. Chỉ vài dòng ngắn cũng đủ để sau này bạn nhớ lại chuyến đi bằng cảm giác chứ không chỉ bằng hình ảnh.',
  },

  {
    category: 'CULTURE',
    title: 'Văn hóa chào hỏi và ứng xử khi ghé thăm làng nghề truyền thống',
    excerpt: 'Tôn trọng người làm nghề, không tự ý chạm vào sản phẩm và hỏi trước khi chụp ảnh là những nguyên tắc nhỏ nhưng quan trọng.',
    imageUrl: imageUrl('photo-1494526585095-c41746248156'),
    author: AUTHORS[0],
    readTime: 7,
    publishedAt: new Date('2026-03-22T08:00:00.000Z'),
    focus: 'Ứng xử tại làng nghề',
    destination: 'các làng nghề Việt Nam',
    practicalTip: 'Khi vào xưởng, hãy đi theo khu vực được hướng dẫn, hỏi trước khi quay video và ưu tiên mua sản phẩm chính gốc nếu bạn thật sự yêu thích món đồ đó.',
  },
  {
    category: 'CULTURE',
    title: 'Một ngày ở Huế: đọc lịch sử qua nhịp sống chậm',
    excerpt: 'Huế không chỉ có di tích. Thành phố này còn có cách sống, giọng nói, món ăn và sự điềm tĩnh rất riêng.',
    imageUrl: imageUrl('photo-1528127269322-539801943592'),
    author: AUTHORS[1],
    readTime: 8,
    publishedAt: new Date('2026-03-20T08:00:00.000Z'),
    focus: 'Văn hóa Huế',
    destination: 'Huế',
    practicalTip: 'Đừng chỉ ghé Đại Nội rồi rời đi. Hãy dành thời gian cho chợ, quán chè, những con đường ven sông và các nhà vườn để hiểu thêm về nhịp sống Huế.',
  },
  {
    category: 'CULTURE',
    title: 'Hội An sau ánh đèn lồng: những lớp văn hóa giao thương',
    excerpt: 'Phố cổ Hội An đẹp vì kiến trúc, nhưng sâu hơn là câu chuyện của thương cảng, cộng đồng và sự giao thoa qua nhiều thế kỷ.',
    imageUrl: imageUrl('photo-1559592413-7cec4d0cae2b'),
    author: AUTHORS[2],
    readTime: 8,
    publishedAt: new Date('2026-03-18T08:00:00.000Z'),
    focus: 'Di sản Hội An',
    destination: 'Hội An',
    practicalTip: 'Nên đi phố cổ vào sáng sớm để thấy nhịp sinh hoạt địa phương trước khi đông khách. Buổi tối phù hợp để cảm nhận ánh sáng, âm thanh và đời sống du lịch.',
  },
  {
    category: 'CULTURE',
    title: 'Trang phục phù hợp khi tham quan đền, chùa và di tích',
    excerpt: 'Ăn mặc phù hợp không chỉ để được vào điểm tham quan, mà còn thể hiện sự tôn trọng không gian tín ngưỡng và cộng đồng địa phương.',
    imageUrl: imageUrl('photo-1548013146-72479768bada'),
    author: AUTHORS[3],
    readTime: 6,
    publishedAt: new Date('2026-03-16T08:00:00.000Z'),
    focus: 'Quy tắc trang phục',
    destination: 'đền chùa và di tích',
    practicalTip: 'Nên mang áo khoác mỏng hoặc khăn lớn nếu lịch trình có điểm tâm linh. Tránh trang phục quá ngắn, gây tiếng ồn lớn hoặc tạo dáng phản cảm trong khu vực linh thiêng.',
  },
  {
    category: 'CULTURE',
    title: 'Chợ địa phương: nơi đọc được đời sống thật của một vùng đất',
    excerpt: 'Chợ không chỉ để mua bán. Đó là nơi thể hiện khẩu vị, lịch sinh hoạt, ngôn ngữ và tính cách cộng đồng.',
    imageUrl: imageUrl('photo-1488459716781-31db52582fe9'),
    author: AUTHORS[4],
    readTime: 7,
    publishedAt: new Date('2026-03-14T08:00:00.000Z'),
    focus: 'Văn hóa chợ',
    destination: 'các đô thị và vùng quê Việt Nam',
    practicalTip: 'Hãy đi chợ vào buổi sáng, hỏi giá lịch sự và không trả giá quá mức với những món hàng giá trị nhỏ. Sự tôn trọng khiến trải nghiệm gần gũi hơn.',
  },
  {
    category: 'CULTURE',
    title: 'Nghệ thuật kể chuyện qua kiến trúc nhà cổ',
    excerpt: 'Nhà cổ lưu giữ nhiều lớp thông tin về khí hậu, gia đình, nghề nghiệp và quan niệm sống của người xưa.',
    imageUrl: imageUrl('photo-1518005020951-eccb494ad742'),
    author: AUTHORS[0],
    readTime: 7,
    publishedAt: new Date('2026-03-12T08:00:00.000Z'),
    focus: 'Kiến trúc nhà cổ',
    destination: 'Hội An, Hà Nội và các làng cổ',
    practicalTip: 'Khi tham quan nhà cổ, hãy quan sát hướng gió, sân trong, chất liệu gỗ và cách bố trí bàn thờ. Những chi tiết này nói nhiều hơn một tấm ảnh toàn cảnh.',
  },
  {
    category: 'CULTURE',
    title: 'Lễ hội địa phương: tham gia thế nào cho văn minh?',
    excerpt: 'Lễ hội là trải nghiệm văn hóa sống động, nhưng du khách cần hiểu ranh giới giữa quan sát, tham gia và làm phiền nghi thức.',
    imageUrl: imageUrl('photo-1533174072545-7a4b6ad7a6c3'),
    author: AUTHORS[1],
    readTime: 8,
    publishedAt: new Date('2026-03-10T08:00:00.000Z'),
    focus: 'Ứng xử tại lễ hội',
    destination: 'các lễ hội truyền thống',
    practicalTip: 'Trước khi tham gia, hãy tìm hiểu ý nghĩa lễ hội, khu vực nào dành cho khách và khu vực nào chỉ dành cho nghi thức. Không chen lấn để chụp ảnh ở vị trí nhạy cảm.',
  },
  {
    category: 'CULTURE',
    title: 'Âm thanh của phố cổ: từ tiếng rao đến tiếng chuông chùa',
    excerpt: 'Một nơi chốn không chỉ được nhớ bằng hình ảnh. Âm thanh là phần quan trọng tạo nên bản sắc và ký ức du lịch.',
    imageUrl: imageUrl('photo-1493246507139-91e8fad9978e'),
    author: AUTHORS[2],
    readTime: 6,
    publishedAt: new Date('2026-03-08T08:00:00.000Z'),
    focus: 'Âm thanh đô thị cổ',
    destination: 'Hà Nội, Hội An và Huế',
    practicalTip: 'Hãy thử tắt tai nghe trong một đoạn đi bộ ngắn. Bạn sẽ nghe thấy nhịp sống địa phương rõ hơn: tiếng xe, tiếng chợ, tiếng gọi nhau và cả khoảng lặng giữa phố.',
  },
  {
    category: 'CULTURE',
    title: 'Quà lưu niệm có trách nhiệm: mua gì để ủng hộ cộng đồng địa phương',
    excerpt: 'Một món quà tốt không chỉ đẹp, mà còn có nguồn gốc rõ ràng, dùng được và hỗ trợ người làm nghề thật sự.',
    imageUrl: imageUrl('photo-1513519245088-0e12902e5a38'),
    author: AUTHORS[3],
    readTime: 6,
    publishedAt: new Date('2026-03-06T08:00:00.000Z'),
    focus: 'Mua sắm có trách nhiệm',
    destination: 'làng nghề và chợ địa phương',
    practicalTip: 'Ưu tiên sản phẩm thủ công có câu chuyện rõ ràng, tránh mua đồ từ vật liệu gây hại môi trường hoặc sản phẩm không rõ nguồn gốc được gắn mác địa phương.',
  },
  {
    category: 'CULTURE',
    title: 'Cách lắng nghe hướng dẫn viên để hiểu sâu hơn về di sản',
    excerpt: 'Hướng dẫn viên giỏi không chỉ đọc thông tin. Họ giúp kết nối hiện vật, câu chuyện và trải nghiệm của du khách.',
    imageUrl: imageUrl('photo-1524492412937-b28074a5d7da'),
    author: AUTHORS[4],
    readTime: 6,
    publishedAt: new Date('2026-03-04T08:00:00.000Z'),
    focus: 'Tham quan di sản',
    destination: 'bảo tàng, di tích và phố cổ',
    practicalTip: 'Hãy đặt câu hỏi cụ thể thay vì chỉ nghe thụ động. Những câu như “chi tiết này có ý nghĩa gì?” hoặc “người địa phương nhìn nơi này ra sao?” thường mở ra câu chuyện hay hơn.',
  },

  {
    category: 'GASTRONOMY',
    title: 'Bản đồ ẩm thực Hà Nội cho người mới bắt đầu',
    excerpt: 'Phở, bún chả, cà phê trứng, cốm và các món quà vặt tạo nên một hành trình vị giác rất riêng của Hà Nội.',
    imageUrl: imageUrl('photo-1551218808-94e220e084d2'),
    author: AUTHORS[0],
    readTime: 8,
    publishedAt: new Date('2026-03-02T08:00:00.000Z'),
    focus: 'Ẩm thực Hà Nội',
    destination: 'Hà Nội',
    practicalTip: 'Nên ăn theo khung giờ địa phương: phở và bún buổi sáng, bún chả buổi trưa, cà phê chiều và món ăn nhẹ buổi tối. Đừng cố ăn quá nhiều món trong một buổi.',
  },
  {
    category: 'GASTRONOMY',
    title: 'Ăn hải sản miền Trung sao cho ngon và an toàn',
    excerpt: 'Chọn quán, hỏi giá, kiểm tra độ tươi và đặt món vừa đủ là những nguyên tắc giúp bữa hải sản trọn vẹn hơn.',
    imageUrl: imageUrl('photo-1565680018434-b513d5e5fd47'),
    author: AUTHORS[1],
    readTime: 7,
    publishedAt: new Date('2026-02-28T08:00:00.000Z'),
    focus: 'Hải sản miền Trung',
    destination: 'Đà Nẵng, Nha Trang và Phú Yên',
    practicalTip: 'Hãy hỏi giá theo cân trước khi gọi món, chọn quán có lượng khách ổn định và tránh ăn quá nhiều đồ sống nếu bạn có hệ tiêu hóa nhạy cảm.',
  },
  {
    category: 'GASTRONOMY',
    title: 'Ẩm thực Huế: nhỏ, tinh tế và nhiều lớp hương vị',
    excerpt: 'Từ bún bò, bánh bèo, bánh nậm đến chè Huế, mỗi món ăn đều thể hiện sự cân bằng giữa vị, màu và cách phục vụ.',
    imageUrl: imageUrl('photo-1504674900247-0877df9cc836'),
    author: AUTHORS[2],
    readTime: 8,
    publishedAt: new Date('2026-02-26T08:00:00.000Z'),
    focus: 'Ẩm thực Huế',
    destination: 'Huế',
    practicalTip: 'Đừng chỉ tìm một món nổi tiếng. Ẩm thực Huế đáng trải nghiệm theo nhóm món nhỏ, mỗi món một chút để cảm nhận sự tinh tế trong nước chấm, topping và cách trình bày.',
  },
  {
    category: 'GASTRONOMY',
    title: 'Cà phê Việt Nam: hơn cả một thức uống',
    excerpt: 'Từ cà phê phin đến cà phê trứng, bạc xỉu và cà phê muối, văn hóa cà phê Việt Nam là một phần đời sống đô thị.',
    imageUrl: imageUrl('photo-1495474472287-4d71bcdd2085'),
    author: AUTHORS[3],
    readTime: 6,
    publishedAt: new Date('2026-02-24T08:00:00.000Z'),
    focus: 'Văn hóa cà phê',
    destination: 'Hà Nội, Sài Gòn và Huế',
    practicalTip: 'Nếu muốn cảm nhận đúng nhịp, hãy ngồi lại thay vì mua mang đi. Một ly cà phê phin cần thời gian, và chính thời gian đó là một phần trải nghiệm.',
  },
  {
    category: 'GASTRONOMY',
    title: 'Chợ đêm và ẩm thực đường phố: ăn thế nào để không quá tải',
    excerpt: 'Ẩm thực đường phố hấp dẫn vì đa dạng, nhưng cần biết chọn món, chia khẩu phần và giữ vệ sinh để chuyến đi không bị gián đoạn.',
    imageUrl: imageUrl('photo-1504754524776-8f4f37790ca0'),
    author: AUTHORS[4],
    readTime: 7,
    publishedAt: new Date('2026-02-22T08:00:00.000Z'),
    focus: 'Ẩm thực đường phố',
    destination: 'các chợ đêm du lịch',
    practicalTip: 'Hãy đi cùng nhóm để chia món, chọn hàng nấu nóng tại chỗ và tránh thử quá nhiều món lạ trong cùng một tối nếu ngày hôm sau có lịch trình dày.',
  },
  {
    category: 'GASTRONOMY',
    title: 'Món ăn theo mùa: cách hiểu một vùng đất qua nguyên liệu',
    excerpt: 'Nguyên liệu theo mùa phản ánh khí hậu, thói quen canh tác và khẩu vị địa phương rõ hơn bất kỳ bảng xếp hạng món ngon nào.',
    imageUrl: imageUrl('photo-1498837167922-ddd27525d352'),
    author: AUTHORS[0],
    readTime: 6,
    publishedAt: new Date('2026-02-20T08:00:00.000Z'),
    focus: 'Ẩm thực theo mùa',
    destination: 'các vùng miền Việt Nam',
    practicalTip: 'Khi đến một nơi mới, hãy hỏi món nào đang vào mùa. Câu hỏi này thường dẫn bạn đến những lựa chọn tươi hơn, đúng địa phương hơn và ít bị du lịch hóa.',
  },
  {
    category: 'GASTRONOMY',
    title: 'Ăn chay khi đi du lịch: chuẩn bị trước để không bị động',
    excerpt: 'Du khách ăn chay vẫn có thể có trải nghiệm ẩm thực tốt nếu tìm hiểu trước khu vực lưu trú, món địa phương và cách gọi món.',
    imageUrl: imageUrl('photo-1512621776951-a57141f2eefd'),
    author: AUTHORS[1],
    readTime: 6,
    publishedAt: new Date('2026-02-18T08:00:00.000Z'),
    focus: 'Du lịch ăn chay',
    destination: 'các thành phố lớn và điểm nghỉ dưỡng',
    practicalTip: 'Nên lưu sẵn vài quán chay gần khách sạn, học cách nói rõ yêu cầu không dùng thịt, nước mắm hoặc nước dùng xương nếu bạn ăn chay nghiêm ngặt.',
  },
  {
    category: 'GASTRONOMY',
    title: 'Bữa sáng địa phương: cách bắt đầu ngày mới như người bản xứ',
    excerpt: 'Bữa sáng là thời điểm tốt nhất để thấy một thành phố vận hành, từ quán phở đông khách đến xe bánh mì bên góc phố.',
    imageUrl: imageUrl('photo-1490645935967-10de6ba17061'),
    author: AUTHORS[2],
    readTime: 5,
    publishedAt: new Date('2026-02-16T08:00:00.000Z'),
    focus: 'Bữa sáng địa phương',
    destination: 'các thành phố Việt Nam',
    practicalTip: 'Hãy dậy sớm hơn lịch trình khoảng ba mươi phút để ăn sáng thong thả. Một bữa sáng tốt giúp bạn hiểu nhịp sống địa phương và có năng lượng cho cả ngày.',
  },
  {
    category: 'GASTRONOMY',
    title: 'Nước chấm: linh hồn thầm lặng của ẩm thực Việt',
    excerpt: 'Từ nước mắm chua ngọt đến mắm nêm, muối tiêu chanh và tương, nước chấm quyết định nhiều tầng hương vị trong món ăn Việt.',
    imageUrl: imageUrl('photo-1504674900247-0877df9cc836'),
    author: AUTHORS[3],
    readTime: 7,
    publishedAt: new Date('2026-02-14T08:00:00.000Z'),
    focus: 'Nước chấm Việt Nam',
    destination: 'ẩm thực ba miền',
    practicalTip: 'Nếu chưa quen vị mắm, hãy thử từng chút thay vì trộn nhiều ngay từ đầu. Nước chấm ngon là để nâng món ăn lên, không phải che lấp toàn bộ hương vị chính.',
  },
  {
    category: 'GASTRONOMY',
    title: 'Mang đặc sản về làm quà: chọn gì để dễ bảo quản và có ý nghĩa',
    excerpt: 'Đặc sản làm quà nên dễ vận chuyển, có hạn sử dụng rõ ràng, phù hợp người nhận và kể được câu chuyện của nơi bạn vừa đi qua.',
    imageUrl: imageUrl('photo-1514516870926-2059892f3929'),
    author: AUTHORS[4],
    readTime: 6,
    publishedAt: new Date('2026-02-12T08:00:00.000Z'),
    focus: 'Đặc sản làm quà',
    destination: 'các điểm du lịch Việt Nam',
    practicalTip: 'Ưu tiên sản phẩm đóng gói kỹ, ghi rõ ngày sản xuất, hạn dùng và cách bảo quản. Nếu bay máy bay, hãy kiểm tra quy định hành lý trước khi mua chất lỏng hoặc đồ có mùi mạnh.',
  },
];

export async function seedArticles(prisma: PrismaClient) {
  for (const article of articles) {
    const slug = slugify(article.title);
    await prisma.article.upsert({
      where: { slug },
      update: {
        category: article.category,
        title: article.title,
        excerpt: article.excerpt,
        content: buildContent(article),
        imageUrl: article.imageUrl,
        author: article.author,
        readTime: article.readTime,
        isFeatured: article.isFeatured ?? false,
        status: ArticleStatus.PUBLISHED,
        publishedAt: article.publishedAt,
        deletedAt: null,
        reviewNote: null,
      },
      create: {
        slug,
        category: article.category,
        title: article.title,
        excerpt: article.excerpt,
        content: buildContent(article),
        imageUrl: article.imageUrl,
        author: article.author,
        readTime: article.readTime,
        isFeatured: article.isFeatured ?? false,
        status: ArticleStatus.PUBLISHED,
        publishedAt: article.publishedAt,
      },
    });
  }

  const counts = await prisma.article.groupBy({
    by: ['category'],
    where: {
      category: { in: ['GUIDES', 'INSPIRATION', 'CULTURE', 'GASTRONOMY'] },
      deletedAt: null,
    },
    _count: { category: true },
    orderBy: { category: 'asc' },
  });

  console.table(
    counts.map((row) => ({
      category: row.category,
      count: row._count.category,
    })),
  );
}
